# Chat status
WAITING_NONE, SET_CHARGE_DAY, SET_CHAT_LANGUAGE, ADD_USER_NAME, ADD_USER_BASE_VALUE,\
    ADD_EXPENSE_NAME, ADD_EXPENSE_CHARGE_DAY, EDIT_USER_NAME, EDIT_USER_BASE_VALUE,\
    EDIT_EXPENSE_NAME, EDIT_EXPENSE_CHARGE_DAY, EDIT_EXPENSE_PAID = range(12)
